### ISSUE TITLE
Suggested OLM version to install is dangerously outdated

### ISSUE THREAD

**Issue by exdx** [k8s-operatorhub/operatorhub.io#38]
**Describe the bug**

The version of OLM suggested to install when installing an operator is 0.14.1, which is very very old and insecure. 
![image](https://user-images.githubusercontent.com/31546601/186432627-2eee5a98-9eb3-405c-a01b-939805b60f95.png)

**What did you expect to see?**
The latest version of OLM would be suggested to install, v0.22.0

**Additional context**
This issue is important because the old version recommend is definitely insecure at this point, and likely won't even work properly.

**Comment by tlwu2013** [comment]
Thanks for filing this issue with us, @exdx.

As of today, the OLM version suggested on `OperatorHub.io` has been updated to v0.22.0
```
curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.22.0/install.sh | bash -s v0.22.0
```

We appreciate your help in raising awareness!

**Comment by dmesser** [comment]
This happens when there is an issue with the GitHub API that is used to determine the latest release of on the OLM project. Its run in the client's browser so it may be subject to rate limiting. I also updated the default fallback version a while ago: https://github.com/k8s-operatorhub/operatorhub.io/commit/345a6e4e9b3cb888ead5e90015b2b5b9d3ae55c9
